### ISSUE TITLE
Scale DriveTrain encoder distance

### ISSUE THREAD

**Issue by jtechau** [AGHSEagleRobotics/frc1388-2023#22]
The DriveTrain subsystem has methods to return the position of the left and right drive motor encoders.  These methods should return the position of the robot in the chosen standard distance units (feet, meters, etc).

It's probably also desirable to add a method (or methods) to reset the position reported by the above methods.

**Comment by AdityaPanikkath** [comment]
Added encoder- needs to be verified with robot and tested

**Comment by AdityaPanikkath** [comment]
Tested
